// Generated by CoffeeScript 1.4.0
(function() {
  var WispCompiler, transpile;

  transpile = require('wisp/lib/engine/node').transpile;

  module.exports = WispCompiler = (function() {

    WispCompiler.prototype.brunchPlugin = true;

    WispCompiler.prototype.type = 'javascript';

    WispCompiler.prototype.extension = 'wisp';

    function WispCompiler(config) {
      this.config = config;
      return;
    }

    WispCompiler.prototype.compile = function(data, path, callback) {
      var error, result;
      try {
        result = transpile(data);
        return result = result.replace(/exports/g, 'module.exports');
      } catch (err) {
        return error = err;
      } finally {
        callback(error, result);
      }
    };

    return WispCompiler;

  })();

}).call(this);
